apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: webapp

build:
  artifacts:
    - image: webapp
      context: webapp
    - image: frontend
      context: frontend

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
