apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            #- mountPath: /docker-entrypoint-initdb.d/
            #  name: init-volume
              
        #- name: webapp
        #  image: webapp
        #  imagePullPolicy: Never # Uses Minikubes Docker image repo (minikube only)
        #  ports:
        #    - containerPort: 3000
        
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        #- name: init-volume
        #  configMap:
        #    name: postgresinit-config